name: Continuous Integration

on:
  push:
    branches: [ "main", "fluxos de trabalho" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4


      - name: Rodando um teste de CI
        run: echo Hello, world!


      - name: Run a multi-line script
        run: |
          echo "O código foi integrado e testado com sucesso!"
